bank_app/urls.py
from django.urls import path
from . import views
from . import rest_api


app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('admin-dashboard', views.admin_page, name='admin_page'),
    path('customer_dashboard', views.customer_dashboard, name='customer_dashboard'),
    path('customer_dashboard/<int:id>/', views.customer_dashboard, name='customer_dashboard'),
    path('make_loan_request/', views.make_loan_request, name='make_loan_request'),
    path('review_loan_request', views.review_loan_request, name='review_loan_request'),
    path('make_account_request/', views.make_account_request, name='make_account_request'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('add_customer/', views.add_customer, name='add_customer'),
    path('admin-dashboard/<int:id>/decline', views.decline_loan_request, name='decline_loan_request'),
    path('admin-dashboard/<int:id>/approve', views.approve_loan_request, name='approve_loan_request'),
    path('admin-dashboard/<int:id>/decline-account', views.decline_account_request, name='decline_account_request'),
    path('admin-dashboard/<int:id>/approve-account', views.approve_account_request, name='approve_account_request'),
    path('account-details/<int:id>', views.account_details, name='account_details'),
    path('customer_overview/', views.customer_overview, name='customer_overview'),
    path('search_customers/', views.search_customers, name='search_customers'),
    path('change_rank/<int:id>', views.change_rank, name='change_rank'),
    path('get_accounts/', rest_api.get_accounts),
    path('get_account/<int:id>', rest_api.get_account),
    path('transfer_out/', rest_api.transfer_out),
    path('get_transaction/', rest_api.get_transaction),
]

kea_bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from two_factor.urls import urlpatterns as tf_urls


urlpatterns = [
    path('', include(tf_urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/logout/', auth_views.logout_then_login, name='logout'),
    #path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('', include('bank_app.urls'))
]

bank_app/forms.py
from django import forms
from .models import Customer, Account, Bank
from django.forms import ModelForm
from django.contrib.auth.models import User
from .utils import get_ip, test_ip
from django.shortcuts import get_object_or_404


class LoanRequestForm(forms.Form):

    # Ensure loan_amount is positive

    loan_amount = forms.DecimalField(min_value=0)

    def clean_loan_amount(self):
        loan_amount = self.cleaned_data['loan_amount']
        if loan_amount < 0:
            raise forms.ValidationError("Please enter a positive loan amount.")
        return loan_amount


class AccountRequestForm(forms.Form):
    customer = forms.ModelChoiceField(queryset=Customer.objects.all(), widget=forms.HiddenInput())


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ["phone", "rank"]


class AccountModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return f'{obj.id} - {obj.title} ({obj.balance} DKK)'


class TransferForm(forms.Form):
    amount = forms.DecimalField(max_digits=25, decimal_places=2)
    debit_account = AccountModelChoiceField(queryset=Account.objects.all())
    debit_text = forms.CharField()
    credit_account = forms.IntegerField(label="Recipient account number:")
    credit_text = forms.CharField()
    bank = forms.ModelChoiceField(queryset=Bank.objects.all())

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        customer = Customer.objects.get(user=user)
        self.fields['debit_account'].queryset = Account.objects.filter(customer=customer, is_loan=False)

    def clean(self):
        cleaned_data = super().clean()
        amount = cleaned_data.get('amount')
        debit_account = cleaned_data.get('debit_account')
        credit_account_id = cleaned_data.get('credit_account')
        bank_in = cleaned_data.get('bank')

        if amount and debit_account and amount > debit_account.balance:
            self.add_error('amount', 'Amount exceeds balance of selected account.')
        
        bank_out_ip = get_ip()
        bank_in_ip = get_object_or_404(Bank, pk=bank_in.pk).ip_address
        cleaned_data['bank_in_ip'] = bank_in_ip
        cleaned_data['bank_out_ip'] = bank_out_ip
        
        if test_ip(bank_out_ip):
            if bank_out_ip == bank_in_ip: # Internal transfer
                if credit_account_id:
                    try:
                        credit_account = Account.objects.get(id=credit_account_id)
                    except Account.DoesNotExist:
                        self.add_error('credit_account', 'Credit account does not exist.')
                    else:
                        if credit_account == debit_account:
                            self.add_error('credit_account', 'Can not transfer to the same account.')
                        elif credit_account.is_loan and credit_account.customer != debit_account.customer:
                            self.add_error('credit_account', 'Can not transfer to other customer\'s loan account.')
                        cleaned_data['credit_account'] = credit_account
        else:
            self.add_error('bank', 'Something went wrong, try again.')
        return cleaned_data


class CurrencyForm(forms.Form):
    CURRENCY_CHOICES = [
        ('DKK', 'DKK'),
        ('USD', 'USD'),
        ('EUR', 'EUR'),
    ]
    currency = forms.ChoiceField(choices=CURRENCY_CHOICES, label='View your balance in different currencies:', widget=forms.Select(attrs={'onchange': 'this.form.submit();'}))

bank_app/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string
from .models import Customer, LoanRequest, AccountRequest, Ledger, Account, ApprovedLoanRequests, ApprovedAccountRequests, Rank, Bank, Transaction, UserProfile 
from .forms import LoanRequestForm, AccountRequestForm, UserForm, CustomerForm, TransferForm, CurrencyForm
from .rest_api import transfer_out
from.utils import get_ip, test_ip
from django.db import IntegrityError, transaction
from secrets import token_urlsafe
import requests
from .serializers import TransferSerializer
from rest_framework.renderers import JSONRenderer
import uuid
from django.conf import settings
from .utils import convert_currency
from sms import send_sms

@login_required
def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank_app:admin_page'))
    else:
        return HttpResponseRedirect(reverse('bank_app:customer_dashboard'))


@login_required
def admin_page(request):
    customers = Customer.objects.all()
    users = User.objects.all()
    loan_requests = LoanRequest.objects.all()
    account_requests = AccountRequest.objects.all()
    approved_loan_requests = ApprovedLoanRequests.objects.all()
    accounts = Account.objects.all()
    context = {
        'customers': customers,
        'accounts': accounts,
        'approved_loan_requests': approved_loan_requests,
        'users': users,
        'loan_requests': loan_requests,
        'account_requests': account_requests,
    }
    return render(request, 'bank_app/admin_page.html', context)


@login_required
def customer_dashboard(request, id=''):
    if request.user.is_staff:
        customer = Customer.objects.get(user=id)
    else:
        customer = Customer.objects.get(user=request.user)
    rank = customer.rank
    loan_requests = LoanRequest.objects.filter(customer=customer)
    account_requests = AccountRequest.objects.filter(customer=customer)
    accounts = Account.objects.filter(customer=customer)
    admin_customer = True if request.user.is_staff and customer.user == request.user else False

    form = CurrencyForm(request.POST or None)
    if form.is_valid():
        selected_currency = form.cleaned_data['currency']
        conversion_rate = convert_currency('DKK', selected_currency)
        if 'currency' not in request.session:
            request.session['currency'] = 'DKK'
        else: 
            request.session['selected_currency'] = selected_currency
    else:
        conversion_rate = 1.0

    context = {
        'admin_customer': admin_customer,
        'customer': customer,
        'accounts': accounts,
        'ranks': Rank.objects.all(),
        'rank': rank,
        'loan_requests': loan_requests,
        'account_requests': account_requests,
        'conversion_rate': conversion_rate,
        'form': form,
    }

    return render(request, 'bank_app/dashboard.html', context)



def send_request_notification(user, req, adminphones):
    if (adminphones == []):
        return
    send_sms(
    f'{user} has requested a new {req}',
    '+13158886854',
    f'{adminphones}',
    fail_silently=False
    )

def get_all_admin_phones():
    adminphones = []
    for user_profile in UserProfile.objects.all():
        adminphones.append(user_profile.phone)
    return adminphones


@login_required
def make_loan_request(request):
    if request.method == 'POST':
        if request.user.customer.rank.value < settings.CAN_LOAN:
            context = {
                'error': '* Your rank is unfortunately too low to make a loan request',
            }
            return HttpResponseBadRequest(render(request, 'bank_app/make_loan_request.html', context))
        form = LoanRequestForm(request.POST)
        if form.is_valid():
            LoanRequest.objects.create(customer=request.user.customer, loan_amount=request.POST['loan_amount'])
            send_request_notification(request.user.customer.full_name, "loan", get_all_admin_phones())
            return HttpResponseRedirect(reverse('bank_app:customer_dashboard'))
        else:
            context = {
                'error': '* Please enter a positive loan amount',
            }
            return HttpResponseBadRequest(render(request, 'bank_app/make_loan_request.html', context))
    return render(request, 'bank_app/make_loan_request.html')


@login_required
def make_account_request(request):
    customer = request.user.customer
    form = AccountRequestForm(initial={'customer': customer})
    if request.method == 'POST':
        form = AccountRequestForm(request.POST)
        if form.is_valid():
            customer = form.cleaned_data["customer"]
            try:
                AccountRequest.objects.create(customer=customer)
                send_request_notification(customer.full_name, "account", get_all_admin_phones())
                return HttpResponseRedirect(reverse('bank_app:customer_dashboard'))
            except IntegrityError:
                return IntegrityError
        else:
            return render(request, 'bank_app/make_account_request.html', {'form': form})
    else:
        return render(request, 'bank_app/make_account_request.html', {'form': form})


@login_required
@require_http_methods(['DELETE'])
def decline_loan_request(request, id):
    loan_request = get_object_or_404(LoanRequest, id=id)
    try:
        loan_request.delete()
        return HttpResponse("<button disabled>Declined</button>", content_type="text/html")
    except IntegrityError:
        return HttpResponse(status_code=500)


@login_required
@require_http_methods(['POST'])
def approve_loan_request(request, id):
    assert request.user.is_staff, 'Customer user routing staff view.'
    loan_request = get_object_or_404(LoanRequest, id=id)
    assert loan_request.customer.rank.value >= settings.CAN_LOAN, 'Customer rank too low to approve account request.'
    try:
        with transaction.atomic():
            loan_request.status = "approved"
            loan_request.save()
            # If customer has accout use transfer to that account, if not create an account
            if Account.objects.filter(customer=loan_request.customer).exists():
                customer_account = Account.objects.filter(customer=loan_request.customer).first()
            else:
                customer_account = Account.objects.create(customer=loan_request.customer, title="Account 1", is_loan=False)
            # create account for loan
            loan_i = Account.objects.filter(customer=loan_request.customer, is_loan=True).count() + 1
            loan_account = Account.objects.create(customer=loan_request.customer, title=f"Loan {loan_i}", is_loan=True)
            # add loan_requests to approved_loan_requests
            ApprovedLoanRequests.objects.create(loan_request=loan_request, account=loan_account, approved_by=request.user)
            bank_ip = get_ip()
            if (test_ip(bank_ip)):
                # information for ledger
                amount = loan_request.loan_amount
                debit_account = loan_account
                debit_text = "Approved " + loan_account.title
                credit_account = customer_account
                credit_text = "Approved " + loan_account.title
                bank = Bank.objects.get(ip_address=bank_ip)
                uid = uuid.uuid4()
                # create ledger
                Ledger.transfer(amount, debit_account, debit_text, credit_account, credit_text, uid, bank, is_loan=True)
                return HttpResponse("<button disabled>Approved</button>", content_type="text/html")
            else:
                # TODO: handle error for user
                print("Bank IP not found")

    except IntegrityError:
        return HttpResponse(status_code=500)


@login_required
@require_http_methods(['DELETE'])
def decline_account_request(request, id):
    account_request = get_object_or_404(AccountRequest, id=id)
    try:
        account_request.delete()
        return HttpResponse("<button disabled>Declined</button>", content_type="text/html")
    except IntegrityError:
        return HttpResponse(status_code=500)


@login_required
@require_http_methods(['POST'])
def approve_account_request(request, id):
    try:
        account_request = get_object_or_404(AccountRequest, id=id)
        with transaction.atomic():
            account_request.status = "approved"
            account_request.save()

            # create account for account, and account for use
            account = Account.objects.create(customer=account_request.customer, title="Account")

            # add account_requests to approved_account_requests
            ApprovedAccountRequests.objects.create(account_request=account_request, account=account, approved_by=request.user)

            return HttpResponse("<button disabled>Approved</button>", content_type="text/html")
    except IntegrityError:
        return HttpResponse(status_code=500)


@login_required
def review_loan_request(request):

    loan_request = LoanRequest.objects.all()
    context = {
        'loan_request': loan_request
    }
    return render(request, 'bank_app/review_loan_request.html', context)


@login_required
def add_customer(request):
    if request.user.is_staff:
        user_form = UserForm()
        customer_form = CustomerForm()

        context = {
            'user_form': user_form,
            'customer_form': customer_form
        }

        if request.method == 'POST':
            user_form = UserForm(request.POST)
            customer_form = CustomerForm(request.POST)
            if user_form.is_valid() and customer_form.is_valid():
                username = user_form.cleaned_data["username"]

bank_app/templates/bank_app/account_details.html
{% extends "base.html" %}

{% block main %}

<h1>Account details</h1>
<h2>{{account.title}}</h2>
{% if user.is_staff and customer.user != user %}
<p>Belongs to: <strong>{{ customer.customer_name }}</strong></p>
{% endif %}
<p>Account number: <strong>{{account.id}}</strong></p>
<p>Balance: <strong>{{account.balance}}</strong></p>
<table>
    <thead>
        <tr>
          <th>Amount</th>
          <th>New balance</th>
          <th>Message</th>
          <th>Date</th>
        </tr>
      </thead>
    <tbody>
    {% for i in account.movements %}
    <tr>
        <td>
          {% if i.amount > 0 %}
          +{{i.amount}}
          {% else %}
          {{i.amount}}
          {% endif %}
        </td>
        <td>
          {{i.balance_at_time}}
        </td>   
        <td>{{i.message}}</td>
        <td>{{i.transaction.datetime}}</td>  
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

bank_app/templates/bank_app/add_customer.html
{% extends "base.html" %}

{% block title %}<title>Add new customer</title>{% endblock %}

{% block main %}

<h1>Add a new customer</h1>

{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}
{% if errors %}
    <p>There were errors in the form:</p>
    {{ errors}}
{% endif %}

<form method="post">
    {% csrf_token %}
    <fieldset>
    {{ user_form.as_p }}
    </fieldset>
    <fieldset>
    {{ customer_form}}
    </fieldset>
    <input type="submit" value="Add customer">
</form>

{% endblock %}

bank_app/templates/bank_app/admin_loan_requests.html
{% extends "admin_page.html" %}
{% block loan_requests %}

    <ul id="loan_requests">  {% for loan_request in loan_requests %}
        {% if loan_request.status == "not reviewed" %}
    <li>Customer: {{ loan_request.customer.full_name}}
            id : {{loan_request.id}}
            <br>
            {% if loan_request.status == "approved" %}
            Status: Approved
            {% endif %}
            {% if loan_request.status == "declined" %}
            Status: Declined
            {% endif %}
            {% if loan_request.status == "not reviewed" %}
            status: Not Reviewed
            {% endif %}
            <br>
        Amount: {{loan_request.loan_amount}}
        <br>
        Date: {{loan_request.created_at}}
        <br>

        <button
                hx-swap="outerHTML"
                hx-target="#loan_requests"
                hx-confirm="Are you sure you want to approve this loan?"
                hx-on="htmx:responseError: alert('Error while handling request')"
            hx-patch="{% url 'bank_app:approve_loan_request' loan_request.id %}"
            hx-trigger="click"
            value="approved"
            name="approve_loan_request">
            Approve
        </button>
        <button
                hx-swap="delete"
                hx-target="#loan_requests"
                hx-confirm="Are you sure you want to delete this loan request?"
                hx-on="htmx:responseError: alert('Error while handling request')"
            name="decline_loan_request"
            hx-trigger="click"
            hx-delete="{% url 'bank_app:decline_loan_request' loan_request.id %}"
            value="declined"
            >
            Decline
        </button>
        <button onClick="window.location.href='/review_loan_request/{{loan_request.customer.pk}}';">Review</button>
       </li>
       {% endif %}
        {% endfor %}
    </ul>

{% endblock %}

bank_app/templates/bank_app/admin_page.html
{% extends "base.html" %}

{% block title %}<title>Bank admin</title>{% endblock %}

{% block main %}

<h1>Welcome {{ user }}!</h1>

<section class="">

<div id="loan_requests">
    <h2>Loan Requests</h2>
        <table>
          <thead>
            <tr>
              <th>Id</th>
              <th>Customer</th>
              <th>Status</th>
              <th>Amount</th>
              <th>Date</th> 
              <th></th>
            </tr>
          </thead>
          <tbody>
    {% for loan_request in loan_requests %}
    {% if loan_request.status == "not reviewed" %}
    
    <tr id="loan_request_{{ loan_request.id }}">
        <td>{{loan_request.id}}</td>
        <td>{{ loan_request.customer.full_name}}</td>
        <td> {% if loan_request.status == "approved" %}
        Approved
        {% endif %}
        {% if loan_request.status == "declined" %}
        Declined
        {% endif %}
        {% if loan_request.status == "not reviewed" %}
        Not Reviewed
        {% endif %}</td>
       
        <td>{{loan_request.loan_amount}}</td>
        
        <td>{{loan_request.created_at}}</td>
        
        <td class="button-container">
            <button 
                hx-target="closest .button-container" 
                hx-swap="innerHTML"
                hx-confirm="Are you sure you want to approve this loan request?"
                hx-on="htmx:responseError: alert('Error while handling request')"
                hx-post="{% url 'bank_app:approve_loan_request' loan_request.id %}"
                hx-trigger="click"
                value="approved"
                name="approve_loan_request">
                Approve
            </button>
            <button
                hx-target="closest .button-container"
                hx-swap="innerHTML"
                hx-confirm="Are you sure you want to decline this loan?"
                hx-on="htmx:responseError: alert('Error while handling request')"
                hx-delete="{% url 'bank_app:decline_loan_request' loan_request.id %}"
                name="decline_loan_request"
                hx-trigger="click"
                value="declined"
                >
                Decline
            </button>

        </td>
    </tr>
    {% endif %}
    {% endfor %}
</tbody>
</table>
</div>
</section>
<hr>

<section class="">
<div id="account_requests">
    <h2>Account Requests</h2>

    <table>
        <thead>
          <tr>
            <th>Id</th>
            <th>Customer</th>
            <th>Status</th>
            <th></th>
            <th>Date</th> 
            <th></th>
          </tr>
        </thead>
        <tbody>
    {% for account_request in account_requests %}
    {% if account_request.status == "not reviewed" %}
    <tr id="account_request_{{ account_request.id }}">
        <td> {{account_request.id}} </td>
        <td> {{ account_request.customer.full_name}}</td>
        <td>{% if account_request.status == "approved" %}
        Approved
        {% endif %}
        {% if account_request.status == "declined" %}
        Declined
        {% endif %}
        {% if account_request.status == "not reviewed" %}
        Not Reviewed
        {% endif %}</td>
        <td>
        {{account_request.account_amount}}</td>
        <td>
        {{account_request.created_at}}</td>
        <td class="button-container">
            <button hx-target="closest .button-container" 
                hx-swap="innerHTML"
                hx-confirm="Are you sure you want to approve this account request?"
                hx-on="htmx:responseError: alert('Error while handling request')"
                hx-post="{% url 'bank_app:approve_account_request' account_request.id %}" 
                hx-trigger="click"
                value="approved" name="approve_account_request">
                Approve
            </button>
            <button hx-target="closest .button-container" 
                hx-swap="innerHTML"
                hx-confirm="Are you sure you want to decline this account request?"
                hx-on="htmx:responseError: alert('Error while handling request')"
                hx-delete="{% url 'bank_app:decline_account_request' account_request.id %}" 
                value="declined">
                Decline
            </button>
        </td>
    </tr>
    {% endif %}
    {% endfor %}
</tbody>
</table>
</div>
</section>
<hr>

<section class="grid-2">

<div id="approved_loan_requests">
    <h2>Approved loans</h2>
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Customer</th>
          <th>Title</th>
          <th>Amount</th>
          <th >Approved by</th>
        
        </tr>
      </thead>
    <tbody>
    {% for approved_loan_request in approved_loan_requests %}

    <tr>
        <td>{{approved_loan_request.id}}</td>
        <td>{{approved_loan_request.account.customer.full_name}}</td>
        <td>{{approved_loan_request.account.title}}</td>
       <td>{{approved_loan_request.loan_request.loan_amount}}</td>
       <td>{{approved_loan_request.approved_by}}</td>
    </tr>

    {% endfor %}
</tbody>
</table>
</div>





   
    <div id="approved_loan_requests">
         <h2>All Loans</h2>
        <table>
          <thead>
            <tr>
              <th>Id</th>
              <th>Customer</th>
              <th>Title</th>
              <th>Balance</th>
            
            </tr>
          </thead>
        <tbody>
            {% for account in accounts %}
            {% if account.is_loan == True %} 
        <tr>
            <td>{{account.id}}</td>
            <td>{{account.customer.full_name}}</td>
            <td>{{account.title}}</td>
            <td>{{account.balance}}</td>
          
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
    </table>
    </div>
    </section>


    <section class="">
        <h2>All Accounts</h2>
        <div id="approved_loan_requests">
            <table>
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Customer</th>
                  <th>Title</th>
                  <th>Balance</th>
                
                </tr>
              </thead>
            <tbody>
                {% for account in accounts %}
    {% if account.is_loan == False %}
            <tr>
                <td>{{account.id}}</td>
                <td>{{account.customer.full_name}}</td>
                <td>{{account.title}}</td>
                <td>{{account.balance}}</td>
              
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
        </table>
        </div>
        </section>



{% endblock %}

bank_app/templates/bank_app/approved_loan_requests.html
<ul id="approved_loan_requests">
    {% for approved_loan_request in approved_loan_requests %}
</ul>

bank_app/templates/bank_app/customer_overview.html
{% extends "base.html" %}

{% block title %}<title>Customers</title>{% endblock %}

{% block main %}

<h1>Customer overview</h1>
<div>
  <input
      type="search" 
      name="search" 
      class="form-control"
      placeholder="Search Users..." 
      hx-get="{% url 'bank_app:search_customers' %}" 
      hx-on="htmx:responseError: alert('Error while handling request')"
      hx-trigger="keyup changed delay:500ms" 
      hx-target="#search-results" 
      >
</div>

<hr>
<section>
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Rank</th>
          <th>Accounts</th>
          <th>Loans</th>
          <th>Phone</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="search-results">
      {% include "bank_app/partials/search_customer_results.html" %}
      </tbody>
    </table>
</section>

{% endblock %}	

bank_app/templates/bank_app/dashboard.html
{% extends "base.html" %}

{% block title %}<title>{{ user.first_name }}'s Dashboard</title>{% endblock %}

{% block main %}
{% load bank_app_extras %}

<section class="grid-2">
  <div>
  {% if user.is_staff and customer.user != user %}
  <h1>{{ customer.customer_name }}</h1>
  {% else %}
  <h1>Welcome {{ customer.customer_name }}!</h1>
  {% endif %}
  
  {% if not user.is_staff %}
  <p>Account rank: <strong>{{rank.name}}</strong></p>
  {% else %}
  <label for="selected_rank">Rank</label>
  <select x-ref="select"
          id="selected_rank"
          name="selected_rank"
          hx-trigger="change"
          hx-on="htmx:responseError: alert('Rank change failed')"
          hx-post="{% url 'bank_app:change_rank' customer.pk %}"
          hx-swap="innerHTML"
          hx-target="this"
          >
          {% include "bank_app/partials/rank_selector.html" %}
  </select>
  {% endif %}
</div>
<form method="post" >
  <br>
  {% csrf_token %}
    <div>
      {{ form.as_p }}
    </div>
</form>
</section>
<section class="grid-2">
  <div>
    <h2>Accounts</h2>
    <table>
      <thead>
        <tr>
          <th>Number</th>
          <th>Name</th>
          <th class="align-right">Balance</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for account in accounts %}
        {% if account.is_loan == False %}
        <tr>
          <td>{{ account.id }}</td>
          <td>{{ account.title }}</td>
          <td class="align-right">{{ account.balance|floatformat:2|mul:conversion_rate }} {{ request.session.selected_currency }}</td>
          <td class="float-right" ><a href="{% url 'bank_app:account_details' account.id %}">More</a></td>
        </tr>
        {% endif %}
        {% empty %}
        <p>No accounts</p>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div>
    <h2>Loans</h2>
    <table>
      <thead>
        <tr>
          <th>Number</th>
          <th>Name</th>
          <th class="float-right">Balance</th>
        </tr>
      </thead>
      <tbody>
        {% for loan in accounts %}
        {% if loan.is_loan == True %}
        <tr>
          <td>{{loan.id }}</td>
          <td>{{loan.title}}</td>
          <td class="align-right">{{ loan.balance|floatformat:2|mul:conversion_rate }} {{ request.session.selected_currency }}</td>
        </tr>
        {% endif %}
        {% empty %}
        <p>No loans</p>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>

<hr>
<br>
<h2>Pending requests</h2>
    <blockquote>Please note that each request must be approved by an employee before it can be processed</blockquote>
<section class="grid-2">
  <div>
    <h3>Account requests</h3>
      <ul>
        {% for account_request in account_requests %}
          {% if account_request.status == "not reviewed" %}
            <li>Requested: {{account_request.created_at}}</li>
          {% endif %}
          {% empty %}
          <p>No pending account requests</p>
          {% if user.is_staff == False or admin_customer %}
          <button><a href="{% url 'bank_app:make_account_request' %}">Apply for an account</a></button>
          {% endif %}
        {% endfor %}
      </ul>
      </tbody>
    </table>
  </div>
  <div>
    <h3>Loan requests</h3>
        {% for loan_request in loan_requests %}
          {% if loan_request.status == "not reviewed" %}
          <ul>
            <li><span>Requested: {{loan_request.created_at}} </span><strong> {{ loan_request.loan_amount|floatformat:2|mul:conversion_rate }} {{ request.session.selected_currency }}</strong></li>
          </ul>
          {% endif %}
          {% empty %}
          <p>No pending loan requests</p>
          {% if user.is_staff == False or admin_customer %}
          <button><a href="{% url 'bank_app:make_loan_request' %}">Apply for a loan</a></button>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
{% endblock %}

bank_app/templates/bank_app/loan_request.html
{% extends 'base.html' %}

{% block main %}
    <h2>List of all loans:</h2>
    <ul>
    {% for loan in loans %}
        <li>Loan amount: {{ loan.loan_amount }}</li>
    {% empty %}
        <li>No loans found.</li>
    {% endfor %}
    </ul>

    <h2>List of approved loans:</h2>
    <ul>
    {% for loan in approved_loans %}
        <li>Loan amount: {{ loan.loan_amount }}</li>
    {% empty %}
        <li>No approved loans found.</li>
    {% endfor %}
    </ul>
{% endblock %}